name: cd
on:
  push:
    branches:
    - 'main'
    - 'master'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout git repository
              uses: actions/checkout@v2
            - name: Setup dotnet
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: '7.0.x'
            - name: Build solution
              run: dotnet build
            - name: Test solution
              run: dotnet test
            - name: Publish API
              run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/app
            - name: Deploy to Azure
              uses: azure/webapps-deploy@v2
              with:
                app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
                publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                package: ${{env.DOTNET_ROOT}}/app
                
